import type { Metadata } from "next";
import { PageShell, H2, P, UL } from "@/components/page-shell";

export const metadata: Metadata = {
  title: "Terms of Service — Scientific Quran AI",
  description: "Terms of use for Scientific Quran AI.",
};

export default function TermsPage() {
  return (
    <PageShell
      title="Terms of Service"
      subtitle="Effective 2026-05-12. By using Scientific Quran AI you agree to the following."
    >
      <H2>What this service is</H2>
      <P>
        Scientific Quran AI is a research and study aid that answers your
        questions using the Holy Quran (primary authority), the scientific
        tafsir of Zakaria Kamal (secondary authority), and authentic Hadith /
        the Bible (contextual references only). It is built and maintained
        independently by Zasif Bin Islam.
      </P>

      <H2>Not a fatwa, not a fiqh ruling</H2>
      <P>
        The answers generated by this service are produced by a large language
        model (Google Gemini) operating over a curated knowledge base. They
        are{" "}
        <strong>
          not a substitute for consultation with a qualified scholar (ʿālim,
          mufti)
        </strong>{" "}
        and should not be relied upon as a binding fatwa or fiqh ruling on
        personal matters. For sensitive personal, legal, or theological
        decisions, always consult a competent human scholar.
      </P>

      <H2>Accuracy and limitations</H2>
      <UL>
        <li>
          The AI may make mistakes, miscite ayat, or misrepresent scholarly
          opinions despite our best efforts. Verify important claims against
          primary sources.
        </li>
        <li>
          The Bible is included only for comparative or historical context.
          The service does not treat it as a source of Islamic ruling.
        </li>
        <li>
          The knowledge base reflects the texts ingested (Quran + Zakaria
          Kamal&apos;s tafsir + Sahih al-Bukhari + KJV Bible). Other valuable
          scholarship is not present and the absence of an opinion in the
          answers does not mean that opinion does not exist.
        </li>
      </UL>

      <H2>Acceptable use</H2>
      <P>You agree not to:</P>
      <UL>
        <li>
          Use the service to spread defamation, hatred, or violent extremism.
        </li>
        <li>
          Attempt to abuse the rate limits, the AI providers&apos; APIs, or the
          subscription system (e.g. fake transaction IDs).
        </li>
        <li>
          Scrape, mirror, or commercially redistribute the chat outputs as if
          they were authoritative rulings.
        </li>
        <li>
          Reverse-engineer the service&apos;s prompts or internal data for
          competitive purposes.
        </li>
      </UL>

      <H2>Free tier</H2>
      <P>
        The service is free to use within rate limits imposed by our free-tier
        AI providers (currently roughly 40 messages per minute across all
        users combined). If you hit the limit, the UI will pause for up to 60
        seconds and offer the subscription option.
      </P>

      <H2>Subscription (৳300 / 3 months)</H2>
      <UL>
        <li>
          The subscription removes per-user rate limits and includes web-search
          grounding usage.
        </li>
        <li>
          Payment is collected manually via bKash. Activation occurs within 24
          hours of payment verification.
        </li>
        <li>
          Subscriptions are non-refundable except in cases of service-side
          failure where the subscription period was not delivered.
        </li>
        <li>
          The subscription does not entitle you to a guarantee of correctness
          or to a particular AI model — providers may change as cost or
          quality conditions change.
        </li>
      </UL>

      <H2>Service availability</H2>
      <P>
        The service is provided &quot;as is&quot; on a best-effort basis. We
        do not guarantee uninterrupted availability. Free-tier infrastructure
        may go down. Subscribers will be credited additional time for material
        outages on request.
      </P>

      <H2>Liability</H2>
      <P>
        To the maximum extent permitted by law, Scientific Quran AI and its
        operator are not liable for any decision you make on the basis of an
        AI-generated answer. You are responsible for your own actions and for
        consulting human scholars on important matters.
      </P>

      <H2>Changes</H2>
      <P>
        Material changes to these terms will be announced in the chat sidebar
        and reflected in the &quot;Effective&quot; date above.
      </P>

      <H2>Contact</H2>
      <P>
        Disputes or questions:{" "}
        <a
          href="mailto:zasifbinislam@gmail.com"
          className="text-accent underline underline-offset-4"
        >
          zasifbinislam@gmail.com
        </a>
        .
      </P>
    </PageShell>
  );
}
